apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-push-template
spec:
  params:
    - name: git-repo-url
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: inventory-pipeline-run-
      spec:
        pipelineRef:
          name: cd-pipeline
        params:
          - name: url
            value: $(params.git-repo-url)
          - name: revision
            value: $(params.git-revision)
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: your-pvc-name
